### ISSUE TITLE
Switch `bumaplo` with `bump-scope` in oxc

### ISSUE THREAD

**Issue by Boshen** [bluurryy/bump-scope#37]
Hi! I'm the author of [Oxc](https://github.com/oxc-project/oxc), where we are building a collection of high-performance tools for JavaScript in Rust.

I'm reaching out for the possibility of switching `bumpalo` to `bump-scope` for performance improvements.

Here is our [research issue](https://github.com/oxc-project/backlog/issues/49) for more context.

Since there will definitely be missing pieces, the best way is to let you play around with switching out `bumpalo` in our [oxc_allocator](https://github.com/oxc-project/oxc/tree/main/crates/oxc_allocator) crate and see how it goes, and we'll aid you in the process.

If you are interested, may I invite you to our [discord](https://discord.com/invite/9uXCAwqQZW) to establish a communication channel?

**Comment by bluurryy** [comment]
That sounds interesting, I'll take a look. I've joined the discord channel.

**Comment by Boshen** [comment]
PR: https://github.com/oxc-project/oxc/pull/6668
